---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull-secret
  namespace: site-api
spec:
  encryptedData:
    .dockerconfigjson: AgCLPV43RsFVEtohaJG14k4fg1OpGNrmZ4WARnTirT9IG9oo4K1q/EPNXDw+HeK7VHmWZfW4BNwIFHR4WUr3T0tslXGlvV6I5mz2G6WSWyoM2YXc46wj4ftUns8RWpLESRKf3NJfjowzkVZs1HKo8JGC7OGiXIeTaYJLHGTxft+riqwLC85nvTjygWhVCHjCyf1n+NhN/5c/uQP9knpSHmSMkAhfg1JfCboEurXcc1+s4+No27cnc2T2dieHHQFmcrdqVfhRu/RUrpSPxMECg8MWdCQs8Ak+jE3K0FqsbUDL/OHbCbs9vzFPjcChvixJ4IJAa1NBK99hLkxc1K9KFI1VrFDCWWjl94cReTBVDG6ODTb2GyE711BxuzNgC6X8efB+nN+pifCm/FSxkiX2lTrNxbvmkm5JK8qvY00IG2+H4zyw4mUT06QRO75xmTS4LVlPvQ/glUxw7LOO44L1UHSGNGiyjV8MXUqZwViXsvzHBfhbtO9sahSjET2Ngkumt1qTlXms3KcYsFJCw4lrhe/RrFZZL6kMkuJLBFbdRmqWxlL29LII/Pi8aCikf09gCws6iZWs2zf1/r9SoFA1RT0r8ubcX9w12hBotCBq4dQ3wSAGmIRyXFTuCs+2mMNef3n7bwdIiLiJ8Vs2ek4YeE8iiE9LdpJvR7clCJtqxlnpFGfSw+U1YWbOQ+h9ZzBNyWNhS15Lc86WtpffIRClawxFGgnrASxNsBqK/ucJ0jBt4wGGkyjeF2mx8Rc42777kNIZPnJozVwl0grGRSRZ2jqVufXtSApgssoj3NcGrvBag2yH48WvYu719G2OraZ21TZSDvaQE8CYPq9pE5qgmxbR07ty6FwKD7jdr8y4Gu5D9b+LK7Inf/S2sQjOo1KjCq2OdVR5ABQFbdIo074VivtaAVNiquJSH/om21tEmMDx5V539EKYqBtJxUCD1/kvIrjyyfw=
  template:
    metadata:
      name: registry-pull-secret
      namespace: site-api
    type: kubernetes.io/dockerconfigjson
