---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: site-api-storage
  namespace: site-api
spec:
  encryptedData:
    access-key: AgChr2g0m18Uaoi/Y9uNWIk1LvYfwUtvz6B3pP4Bm5nfln1XWFiC3kdUZl5Ai9XA8lAw+MwAcXd9xYyIVtQMWjkC8t3ZlLqawCk/Gt27hX6ihmlGDWCc2wujlc6oQF9mXtwhP0KAoqzh5Hj13UVwq4EDgSRfi8qYHu5D41hd5DGIRvt07zvTLGiZ8Irp6GB/w2QMwC1HFlvavqEf2ICu+Epk8e715Aq4EjQV92TRI8Z4eTS3xHVfHE4g9fWM71VpLIqYgt+5ClFsIMLC00I8QmzDHSBkzkSqdL5uokbGeYGxWR9vP+6oXgTfSQTtSS1B8/IXu702mbfCSZqsMq0CuP5K2Y29mB6wKjBWvHLpydQPoLaKi5mPYnkcH93d9vJ3xOZ/8bXdXrkFJOIqvRhc2x9q+BZozy1hvNpNVm5FuMJLp5kG5j98RsD7/sSACRq81jtAPTIvhWjuyWC5+maF9h1m9ctfP/vkW8Wl4PoZU6lXQVY/jEzw5JZvxJhf4zOhGj/QJIHtkwal0jvMI5SrITMrMDC48jEzM4V+qAoQkzv7EQjOpPyNMmL9EO426wKPq2kJyTFfsnZfhSMZQdT7RadlICLCtwrX5uZWtjbaGtPzfb+TtsiLzkh7yW4+E4zBc7jyebje0SSMqCu8reksjbtRGBb6JU9BHv6SkjjWhEYpoEEFpOSYyX8A7YCfV5RygZGui5yi7fBHMUdwFNniEP5yrcMbgTmRPVQZeSM+AbALIQ==
    secret-key: AgDHUHuqWgtr8xKt2+fQiK6QZk57ou/Az1SYPR3SxFZAa2dZwkGZmEsQ2rqxcWKwxPyBpj4FhqhjzNkAHVnzuc+HNeY1E+3mE54mSkuk65JCkIhmz6XVKqriTMipoyPcUHKhHXr6tKzsGHfiycd7wqtLk2oJnf6jDrMiFhg2ZjuVnPZchzkSwaUr4CYRC3FqVBNFZNnxBcckCzaPUoqMNqpeVRZRbq1xcqChse1n8VNsRSsQsd3WV1CYFWXU9RFUghEPnzb5X1r83hSdYwIbVfDD5Otbtqbv6YKgnfWip4gxWWNdsVkzhBfQ3j7qVDgJ6Nv20BluVWtFTMJ5s/i4HDXO6bBG3zEf8hSfh8L3dciA9uCWmgPrTCDJwMrs/1dvd/NDmOzKg7a/oL6z5miPiyJ5kjfQbTH7Luj7KK6N0IN8JcjHr0x98pycnUekCUB1szSwHRPgMg0yQSiTcYwVbs5QJdNt5Pw0peckHnXr7tiN4OxnFHzvpq0e7FEsF63N3ytQvTuE+wi5jSfJ4rhNPGRO6Qjo8HzjmgTUATGi0WEK8H22T//jpvhLu8THxTIHCggDwQsm4x+/kB050Gv0bNou3vppdkPTj/TiaHOxxUFUEXpUkoW/31IjJMOEJZho71e8t8kar4lQ3cq1HlsDmJuI0zdiflz0fjKh5chtT75sIUIdDGnxXHfImgakqT+Hf7xfvGLYUJEw3zWKZC4dak3uWH+xWk7xRZsnAUh2T+AVGMDwWT045j/5q5aCGNgysA4Ct/aYejJwnTEHILY/6A8s
  template:
    metadata:
      name: site-api-storage
      namespace: site-api
