---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: site-api-resend
  namespace: site-api
spec:
  encryptedData:
    api-key: AgAR8ibNhaWALwnMZDw/39vh8ZnaE/BYfCrSZWqjPOOZMSLw18WzMC79oBLkMVFuOOy+4hymTg1dTfcksdq3hEKg6l+aSNgS0bd7b+z18j4vW7yo9f8vGvnax48bNFnXNaMNv3I3FrCqsca6GMloER7EUuosVF/qIfnAnfQxESqIJLK6rVtVMBF6cYj4K6VU/805y1AWGqG5phGLbfL7OgszyAXlTnxCoFmdsgMg1M4yuwex39jfsfn85R61vbuy4hedFE+nlCeBm01mwkhA7svDnN9Ep3cXcuR1LjJnZKB6b6DGqjSxX0oZu/hOAM8hSyBq8noLu0ltqaJrQOW0Ls08RhekheJ8hCN1x+71T6HgGcYZHH/JBh+GCFejNa39IQe2lLXKXLkmaJuoL1NryJTM2++xxpf5veVbUP36kE6EOsiDqfiQYCbPYfM1QRtAkpWbtKVcO9wdrkqweo/TPBf6aJNyEBkuzngNj4upIlOl7juLFPa3c8cy3hLDlrwTGKem5YGoEfZJZIH05L585FO02+yZr0+XmrliMS7ZSGI1UDecgtaZ6RjX2wbwB4mjvgyCOIf8Gxnlvr2gmjDht7xjQe0ig464LpnK+tmJvE33X1M0GI27zyVi0b9ffshknObSxIn9GDFNE+9HVweOwuaHYsceuLJ5IvsWbNgLOgWPCOUYLctJNK02x5WufkMUdMLqaYbz5LB3kNRhcW/vHEifcWJD0xzXmAa8T7CYjnuGzhFFtaQ=
  template:
    metadata:
      name: site-api-resend
      namespace: site-api
