---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: site-api-db-backup
  namespace: site-api
spec:
  encryptedData:
    access-key: AgDvlhyzguFXd9sRL5RTOz5/KewYIoT993i+CEiefeK399V8Fadh4Q5eLpI2PtMyzBgWtcFwxkV55QWivAqDJ5xkwp8sZJXTB0a9KpGsOa0L+BkVc39SOchD6FI4rQV+pONfl0mw1AbeKCI1tpeV59ozrn6mMbIk5aOIHOlVDtMG/RBn2JAWmWtM1DbCASjD/VDLg/bYAiQSsYzA+lIq371OT/w6yoVvQqQFZ/ZzZwCIkXcEvg+46jGB4SmZkHHLzwu1RrQmHP1CA7Czt0Mr3DZEBY0p+Cow6eaTWXo+Ie6r6sHLtLwO8eBTq43IcqOQmskvTCoL3h9xZpNfwci2B70Z2QgaIvBNj2PZREmIpr2/oSIg4DidqwdkButgsiEj0JzxSixXtPEiiGCRFYu4Rwmymfcx2S1GWSWh4xw6E0WNVzsAkLRNxVbtUTt451vlk15TtI8dvFDSYuqwmjjqkb2CBbN+1YIKLRNu4qLljaOsMp9H8FUsmNdiaaKdg+Dx16bJwZDfIl7MHSsEh45fa/3W3TLsm+WxGSbH7CZoBGj275KnPZenM8yw7L07X95aZUFfywC+SnwhgLzjpwz+I0XqQK2BUVPhSD13dpwUvqrtrSXsqt6deGhT9AE5Az69IB3s5Dx8KZ147YemCAWUYqxNKTpQRDMkEmCFaAxxHrFcVyoq2zy5ZCS2/cXtYqSBzaKxODHPN+3B9RD9RShAntDWj7qsoQ==
    secret-key: AgCk9ektXNo/WxaurEx40dlLkAG98pA9+iQXVXt+CAZ5DLnYbtK5P99mkYPCL0FcEcDgZc/S3hVTCALKeQlH8B9N02c+AgDPm+JA47JbcjRKzwfsjGSiW4P3WwLXrlED5VFupxaF3foBX46QbWhC6La4hlnAijDa/WtZVvEgPthTv9bxHXjueQgBixnXoLWYDujAdHz9PH4DjzQ08URHJQn7JGdZ5kTHv4UFkdQjYb55mNu01WDqjQp+SMdJZ1n5BfJImjqXlIrVOB2bw2GXYaX7K3e3CMm8JPnpAgeR5QFT8RktRc1QSw55aWy8Q/9lF4BHZG20ARbZW75gTZfdHnn84DbOtkWOD2Qk/JksfsN29zwNlmxQza4DDvJBpQ9vv+FtNKk4QESUcngFa0arALOEoEZzC/+4GbNSx2RzfiGw+RogSQbOYE4YI6WcrxXt39D6qRmTp+qVS3IC5RPiwuo/r6GHjJAR6Kgm4l0YH61K8R5CMo+IB/qe5DzMBfF+m96TVKmM3Jyw2pz8DqOywKUTUx8gIhZOjip0+pLQYfOnAWW5ZuzWYRMXjFVE1LgDqBJ6nOKy5SRt8V2P9i2gDjXzV46cKJQ1i6N4YwACaaoE4sLXm8ytZENdMmVLbRzyxVc7oILRti6bz18UA2gOlTmBsqTHDj5IhGXwPcpMW9u9/gLR7UIK+Gc2T4WhPRYFux5t0nEPoDHYpoosyLLrDov3GJotqZxEP5ppkkC72nHffPjvPy9WbpC0
  template:
    metadata:
      name: site-api-db-backup
      namespace: site-api
