from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import theme
from .paper import Paper, Publication
from .renderer import IMAGE_H, WhitePaper
from .theme import CONTENT_W

VISUALS_HEADER = {
    "fr": """# Visuels — {title}

Généré par `tools/whitepaper/generate.py {slug}`. Chaque entrée correspond à un
emplacement du document. Les visuels marqués **à produire** sont imprimés dans
le PDF sous forme de cadre décrivant l'attendu.

Format cible des photographies : ratio {ratio:.2f}:1 après recadrage
(la largeur utile du document est de {width:.0f} mm), export ≥ 2000 px de large.
""",
    "en": """# Visuals — {title}

Generated by `tools/whitepaper/generate.py {slug}`. Each entry is one slot in
the document. Visuals marked **to produce** are printed in the PDF as a frame
carrying the brief.

Target format for photographs: {ratio:.2f}:1 after cropping (the document's
usable width is {width:.0f} mm), exported at 2000 px wide or more.
""",
}


@dataclass
class EditionResult:
    paper: Paper
    pdf: Path
    pages: int
    visuals: Path | None
    missing_images: list[str]
    font_notes: list[str]


@dataclass
class BuildResult:
    publication: Publication
    manifest: Path
    editions: list[EditionResult] = field(default_factory=list)


def build_edition(paper: Paper, out_dir: Path, refresh_icons: bool = False) -> EditionResult:
    doc = WhitePaper(paper, refresh_icons=refresh_icons)
    doc.build()
    pdf_path = out_dir / paper.filename
    doc.output(str(pdf_path))
    return EditionResult(
        paper=paper,
        pdf=pdf_path,
        pages=doc.pages_count,
        visuals=write_visuals_brief(paper, out_dir) if paper.images else None,
        missing_images=sorted(set(doc.missing_images)),
        font_notes=doc.font_notes,
    )


def build_publication(pub: Publication, out_root: Path | None = None,
                      refresh_icons: bool = False,
                      langs: tuple[str, ...] | None = None) -> BuildResult:
    out_dir = (out_root or theme.OUT_DIR) / pub.slug
    out_dir.mkdir(parents=True, exist_ok=True)

    editions = [e for e in pub.editions if not langs or e.lang in langs]
    results = [build_edition(e, out_dir, refresh_icons) for e in editions]

    manifest_path = out_dir / "manifest.json"
    # A partial build (--lang) must not zero the page count of the editions it
    # did not produce, so seed from whatever the previous manifest recorded.
    pages = _previous_pages(manifest_path)
    pages.update({r.paper.lang: r.pages for r in results})
    manifest_path.write_text(
        json.dumps(pub.manifest(pages), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return BuildResult(publication=pub, manifest=manifest_path, editions=results)


def _previous_pages(manifest_path: Path) -> dict[str, int]:
    if not manifest_path.exists():
        return {}
    try:
        locales = json.loads(manifest_path.read_text(encoding="utf-8")).get("locales", {})
    except (OSError, ValueError):
        return {}
    return {lang: entry.get("pages", 0) for lang, entry in locales.items()}


def write_visuals_brief(paper: Paper, out_dir: Path) -> Path:
    header = VISUALS_HEADER.get(paper.lang, VISUALS_HEADER["en"])
    lines = [header.format(title=paper.title, slug=paper.slug,
                           ratio=CONTENT_W / IMAGE_H, width=CONTENT_W)]
    available = "disponible" if paper.lang == "fr" else "available"
    to_produce = "**à produire**" if paper.lang == "fr" else "**to produce**"
    status_label = "Statut" if paper.lang == "fr" else "Status"
    caption_label = "Légende" if paper.lang == "fr" else "Caption"
    for key, spec in paper.images.items():
        src = spec.get("path")
        exists = bool(src) and (theme.REPO_ROOT / src).exists()
        status = f"{available} — `{src}`" if exists else to_produce
        lines.append(f"\n## {key}\n")
        lines.append(f"- {status_label} : {status}")
        lines.append(f"- {caption_label} : {spec['caption']}")
        lines.append(f"- Brief : {spec['brief']}")
    path = out_dir / f"visuals-{paper.lang}.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
