// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/articles/ingest/begin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Registers a draft version and returns presigned R2 PUT URLs for the blobs that still need uploading.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Begin an article publish",
                "parameters": [
                    {
                        "description": "Article metadata + built file list",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.IngestBeginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.IngestBeginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/ingest/commit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Verifies all blobs were uploaded, then atomically publishes the version.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Commit an article publish",
                "parameters": [
                    {
                        "description": "Version + job identifiers from begin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.IngestCommitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ArticleDetailResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/{slug}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Removes the article and purges its R2 blobs.",
                "tags": [
                    "admin"
                ],
                "summary": "Delete an article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/admin/whitepapers/ingest/begin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Upserts the publication as a draft and returns presigned PUT URLs for the editions whose PDF is not already stored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Begin a whitepaper publish",
                "parameters": [
                    {
                        "description": "Whitepaper metadata + one entry per language",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperIngestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperIngestResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/admin/whitepapers/ingest/commit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Verifies every edition's PDF is stored, then publishes the whitepaper.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Commit a whitepaper publish",
                "parameters": [
                    {
                        "description": "Slug to publish",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperCommitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/admin/whitepapers/{slug}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Removes the publication and purges its PDFs. Captured leads are kept.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a whitepaper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Whitepaper slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/articles": {
            "get": {
                "description": "Paginated list of published articles/studies with topic, type and full-text filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "List published articles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated types: blog,study",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated topic slugs",
                        "name": "topics",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only featured articles",
                        "name": "featured",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Full-text search over title/summary/body",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "recent | title | featured (default)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Content language: en (default) | fr",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "1-based page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 12, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.PaginatedArticlesResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/articles/{slug}": {
            "get": {
                "description": "Returns article metadata plus the render manifest (entry URL + R2 blob list). Falls back to the canonical locale when the requested translation is absent.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "Get a published article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Article slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Content language: en (default) | fr",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ArticleDetailResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/contact": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a \"Contact us\" submission and triggers the acknowledgement email to the contact plus a notification email to the team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Submit a contact request",
                "parameters": [
                    {
                        "description": "Contact submission",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ContactSubmitReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.ContactSubmitResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/meetings": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a \"30-minute Rendez-vous\" request and triggers the acknowledgement email to the requester plus a notification email to the team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings"
                ],
                "summary": "Request a 30-minute meeting",
                "parameters": [
                    {
                        "description": "Meeting request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.MeetingRequestReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.MeetingRequestResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/topics": {
            "get": {
                "description": "Curated taxonomy with published-article counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "List topics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.TopicResp"
                            }
                        }
                    }
                }
            }
        },
        "/api/whitepapers": {
            "get": {
                "description": "Metadata only. The documents themselves are gated: they are delivered by email after a request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whitepapers"
                ],
                "summary": "List published whitepapers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content language (en, fr)",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only featured whitepapers",
                        "name": "featured",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.WhitePaperResp"
                            }
                        }
                    }
                }
            }
        },
        "/api/whitepapers/{slug}": {
            "get": {
                "description": "Metadata only; never a link to the PDF.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whitepapers"
                ],
                "summary": "Get one published whitepaper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Whitepaper slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Content language (en, fr)",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        },
        "/api/whitepapers/{slug}/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Captures the lead and emails the PDF in the requested language, with a notification to the team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whitepapers"
                ],
                "summary": "Request a whitepaper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Whitepaper slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contact details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperRequestReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.WhitePaperRequestResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ArticleDetailResp": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ManifestFileResp"
                    }
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.AuthorResp"
                    }
                },
                "baseUrl": {
                    "type": "string"
                },
                "canonicalUrl": {
                    "type": "string"
                },
                "coverImage": {
                    "type": "string"
                },
                "coverVideo": {
                    "type": "string"
                },
                "datePublished": {
                    "type": "string"
                },
                "dateUpdated": {
                    "type": "string"
                },
                "entryUrl": {
                    "type": "string"
                },
                "entrypoint": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "longdesc": {
                    "type": "string"
                },
                "readingTime": {
                    "type": "integer"
                },
                "seoDescription": {
                    "type": "string"
                },
                "seoTitle": {
                    "type": "string"
                },
                "shortdesc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TopicResp"
                    }
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "dtos.ArticleSummaryResp": {
            "type": "object",
            "properties": {
                "coverImage": {
                    "type": "string"
                },
                "coverVideo": {
                    "type": "string"
                },
                "datePublished": {
                    "type": "string"
                },
                "dateUpdated": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "readingTime": {
                    "type": "integer"
                },
                "shortdesc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TopicResp"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dtos.AuthorResp": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtos.ContactSubmitReq": {
            "type": "object",
            "required": [
                "email",
                "message",
                "name",
                "phoneNumber",
                "preferredContact",
                "surname"
            ],
            "properties": {
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "linkedinProfile": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "preferredContact": {
                    "type": "string",
                    "enum": [
                        "phone",
                        "email"
                    ]
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "dtos.ContactSubmitResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "dtos.ErrorResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.IngestBeginReq": {
            "type": "object",
            "required": [
                "files",
                "slug",
                "title",
                "type"
            ],
            "properties": {
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "canonicalUrl": {
                    "type": "string"
                },
                "coverPath": {
                    "type": "string"
                },
                "coverVideoPath": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.IngestFileReq"
                    }
                },
                "lang": {
                    "type": "string"
                },
                "longdesc": {
                    "type": "string"
                },
                "readingMinutes": {
                    "type": "integer"
                },
                "seoDescription": {
                    "type": "string"
                },
                "seoTitle": {
                    "type": "string"
                },
                "shortdesc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sourceCommit": {
                    "type": "string"
                },
                "sourceDir": {
                    "type": "string"
                },
                "sourceRef": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dtos.IngestBeginResp": {
            "type": "object",
            "properties": {
                "alreadyPublished": {
                    "type": "boolean"
                },
                "baseUrl": {
                    "type": "string"
                },
                "entrypoint": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uploads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.IngestUploadResp"
                    }
                },
                "version": {
                    "type": "integer"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "dtos.IngestCommitReq": {
            "type": "object",
            "required": [
                "versionId"
            ],
            "properties": {
                "jobId": {
                    "type": "string"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "dtos.IngestFileReq": {
            "type": "object",
            "required": [
                "path",
                "sha256"
            ],
            "properties": {
                "byteSize": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "isEntrypoint": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                }
            }
        },
        "dtos.IngestUploadResp": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "putUrl": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dtos.ManifestFileResp": {
            "type": "object",
            "properties": {
                "byteSize": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "isEntrypoint": {
                    "type": "boolean"
                },
                "kind": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dtos.MeetingRequestReq": {
            "type": "object",
            "required": [
                "email",
                "endDate",
                "message",
                "name",
                "phoneNumber",
                "startDate",
                "surname"
            ],
            "properties": {
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "linkedinProfile": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "dtos.MeetingRequestResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "dtos.PaginatedArticlesResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ArticleSummaryResp"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalBlogPosts": {
                    "type": "integer"
                },
                "totalCaseStudies": {
                    "type": "integer"
                }
            }
        },
        "dtos.TopicResp": {
            "type": "object",
            "properties": {
                "articleCount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "dtos.WhitePaperCommitReq": {
            "type": "object",
            "required": [
                "slug"
            ],
            "properties": {
                "slug": {
                    "type": "string"
                }
            }
        },
        "dtos.WhitePaperIngestReq": {
            "type": "object",
            "required": [
                "locales",
                "slug"
            ],
            "properties": {
                "featured": {
                    "type": "boolean"
                },
                "locales": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dtos.WhitePaperLocaleSpecReq"
                    }
                },
                "publishDate": {
                    "type": "string"
                },
                "requestedBy": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sourceDir": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.WhitePaperIngestResp": {
            "type": "object",
            "properties": {
                "skipped": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "uploads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WhitePaperUploadResp"
                    }
                }
            }
        },
        "dtos.WhitePaperLocaleSpecReq": {
            "type": "object",
            "required": [
                "byteSize",
                "filename",
                "lang",
                "sha256",
                "title"
            ],
            "properties": {
                "byteSize": {
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "longdesc": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer"
                },
                "sha256": {
                    "type": "string"
                },
                "shortdesc": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtos.WhitePaperRequestReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phoneNumber",
                "preferredContact",
                "surname"
            ],
            "properties": {
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "linkedinProfile": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "preferredContact": {
                    "type": "string",
                    "enum": [
                        "phone",
                        "email"
                    ]
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "dtos.WhitePaperRequestResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "dtos.WhitePaperResp": {
            "type": "object",
            "properties": {
                "featured": {
                    "type": "boolean"
                },
                "gated": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "langs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "longdesc": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer"
                },
                "publishDate": {
                    "type": "string"
                },
                "shortdesc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.WhitePaperUploadResp": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "putUrl": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Admin bearer token for the publish (ingest) endpoints. Format: \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "Agency site API",
	Description:      "API for reading agency site resources and triggering contact workflow",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
